from __future__ import annotations

import unittest

from hldspec import engineering_selection as es


class EngineeringTriggerTests(unittest.TestCase):
    def selected_ids(self, hld_text: str) -> set[str]:
        return {card["id"] for card in es.select_p0_cards(hld_text)}

    def test_baseline_cards_always_selected(self):
        ids = self.selected_ids("# HLD\n\nNothing specific here.\n")
        for baseline in es.BASELINE_CARDS:
            self.assertIn(baseline, ids)

    def test_baseline_triggers_report_true_with_no_keywords(self):
        triggers = es.detect_engineering_triggers("# HLD\n\nplain text\n")
        for baseline in es.BASELINE_CARDS:
            self.assertTrue(triggers[baseline])

    def test_http_api_selects_http_json_and_contract_boundary(self):
        ids = self.selected_ids("The service exposes an HTTP API endpoint returning JSON to a client.")
        self.assertIn("api.http_json", ids)
        self.assertIn("testing.contract_boundary", ids)

    def test_bare_api_word_does_not_select_http_json(self):
        # A CLI/library "API" with no HTTP/REST/JSON must not match the HTTP+JSON
        # card (the bare-"api" granularity fix). It is still a contract boundary.
        ids = self.selected_ids("The runner-facing API is a small set of CLI commands.")
        self.assertNotIn("api.http_json", ids)
        self.assertIn("testing.contract_boundary", ids)

    def test_persistence_selects_schema_discipline_and_prod_test_separation(self):
        ids = self.selected_ids("Records are stored in a database with migrations and persistence.")
        self.assertIn("data.schema_discipline", ids)
        self.assertIn("environment.prod_test_separation", ids)

    def test_ui_selects_ui_tester_skill(self):
        ids = self.selected_ids("The UI shows a form with navigation across pages.")
        self.assertIn("testing.ui_tester_skill", ids)

    def test_shared_mutable_data_selects_optimistic_revision(self):
        ids = self.selected_ids("Multiple users edit shared mutable records with revision tracking.")
        self.assertIn("concurrency.optimistic_revision", ids)

    def test_external_integration_selects_hexagonal(self):
        ids = self.selected_ids("The product depends on an external integration and a message bus.")
        self.assertIn("architecture.hexagonal_ports_adapters", ids)

    def test_short_token_does_not_match_inside_word(self):
        # "build" must not trigger the UI card via a substring "ui".
        ids = self.selected_ids("# HLD\n\nWe build a small batch job. No interface.\n")
        self.assertNotIn("testing.ui_tester_skill", ids)

    def test_selection_is_in_canonical_order(self):
        cards = es.select_p0_cards("HTTP API with a database, UI, and shared mutable records.")
        ordered = [card["id"] for card in cards]
        expected = [cid for cid in es.CARD_ORDER if cid in set(ordered)]
        self.assertEqual(ordered, expected)

    def test_every_selected_card_has_evidence(self):
        for card in es.select_p0_cards("HTTP API with a database and UI."):
            self.assertTrue(card["triggered_by"], msg=card["id"])


class EngineeringGuidelinesRenderTests(unittest.TestCase):
    def test_render_includes_required_markers_and_passes_validation(self):
        text = es.render_engineering_guidelines_md(
            "The service exposes an HTTP API over a database with a UI.",
            project_name="demo-target",
        )
        self.assertEqual([], es.validate_engineering_guidelines(text))
        for marker in (
            "# Engineering Guidelines",
            "generated by HLDspec",
            "architecture.business_logic_container",
            "testing.design_for_testability",
            "environment.stage_safe_testing",
            "environment.prod_test_separation",
            "Required architecture shape",
            "Required tests",
            "Forbidden shortcuts",
            "Evidence required",
            "Constitution candidate",
            "Preferred choice",
            "Constitution candidates",
            "Preferred choice selections",
            "selected guidance, not a full toolbox dump",
            "Do not silently overwrite the target constitution",
            "demo-target",
        ):
            with self.subTest(marker=marker):
                self.assertIn(marker, text)

    def test_render_with_minimal_hld_still_valid(self):
        text = es.render_engineering_guidelines_md("# HLD\n\nplain\n")
        self.assertEqual([], es.validate_engineering_guidelines(text))

    def test_validate_flags_stub_content(self):
        errors = es.validate_engineering_guidelines("# Engineering Guidelines\n\n(todo)\n")
        self.assertTrue(errors)


if __name__ == "__main__":
    unittest.main()
