import json
import tempfile
import unittest
from pathlib import Path

from hldspec import hld_source_package as sp
from hldspec import implementation_slicing as slicing

HLD = """# HLD

## HLD-001 - Purpose

HLD-ID: HLD-001
HLD-ROLE: purpose
HLD-STATUS: active
HLD-RISK: LOW

### Purpose
The product has a source-traced implementation flow.
"""


class ImplementationSlicingArtifactTests(unittest.TestCase):
    def test_canonical_slices_include_adapters_and_hardening(self):
        data = slicing.build_implementation_slices()
        names = [item["name"] for item in data["slices"]]
        self.assertEqual(names, list(slicing.SLICE_ORDER))
        for required in ("API", "CLI", "UI", "PERSISTENCE", "BUSINESS_LOGIC"):
            self.assertIn(required, names)

    def test_json_artifact_is_valid_and_every_slice_has_tests(self):
        data = json.loads(slicing.render_implementation_slices_json())
        self.assertEqual(data["schema_version"], slicing.SCHEMA_VERSION)
        for item in data["slices"]:
            self.assertTrue(item["required_tests"], msg=item["name"])
            self.assertTrue(item["allowed_work"], msg=item["name"])
            self.assertTrue(item["forbidden_work"], msg=item["name"])

    def test_policy_states_one_full_flow_many_implementations(self):
        policy = slicing.render_implementation_slicing_policy()
        self.assertIn("one complete specify output", policy)
        self.assertIn("one complete plan", policy)
        self.assertIn("one complete task graph", policy)
        self.assertIn("controlled slices", policy)
        self.assertIn("Do not split the HLD", policy)

    def test_slice_prompt_requires_reads_and_stop_outputs(self):
        prompt = slicing.render_speckit_slice_execution_prompt()
        self.assertIn(".specify/source/HLD.md", prompt)
        self.assertIn(".specify/source/implementation_slices.json", prompt)
        self.assertIn("Selected slice: <SLICE_NAME>", prompt)
        self.assertIn("phase_report.json", prompt)
        self.assertIn("anchor_coverage.json", prompt)
        self.assertIn("Stop after", prompt)

    def test_artifact_set_contains_all_expected_files(self):
        artifacts = slicing.build_implementation_slicing_artifacts()
        for filename in (
            slicing.IMPLEMENTATION_SLICING_POLICY_FILE,
            slicing.IMPLEMENTATION_SLICES_FILE,
            slicing.SLICE_TEST_POLICY_FILE,
            slicing.SPECKIT_SLICE_EXECUTION_PROMPT_FILE,
            slicing.ANCHOR_COVERAGE_SCHEMA_FILE,
        ):
            self.assertIn(filename, artifacts)
            self.assertTrue(artifacts[filename].strip())


class SourcePackageSlicingIntegrationTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.target = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_source_package_writes_and_mirrors_slice_control_artifacts(self):
        build = sp.build_source_package_content(self.target, HLD, hld_source_ref="/src/HLD.md")
        self.assertTrue(build.ok, msg=f"{build.validation.missing} {build.unsupported_claims} {build.marking_errors}")
        source_dir = build.source_dir
        mirror_dir = self.target / ".specify" / "source"

        for filename in (
            "implementation_slicing_policy.md",
            "implementation_slices.json",
            "slice_test_policy.md",
            "speckit_slice_execution_prompt.md",
            "anchor_coverage_schema.json",
        ):
            self.assertTrue((source_dir / filename).is_file(), msg=filename)
            self.assertTrue((mirror_dir / filename).is_file(), msg=filename)

        authoritative_policy = (source_dir / "implementation_slicing_policy.md").read_text(encoding="utf-8")
        mirrored_policy = (mirror_dir / "implementation_slicing_policy.md").read_text(encoding="utf-8")
        self.assertNotIn("GENERATED by HLDspec", authoritative_policy)
        self.assertIn("GENERATED by HLDspec", mirrored_policy)

        json.loads((source_dir / "implementation_slices.json").read_text(encoding="utf-8"))
        json.loads((source_dir / "anchor_coverage_schema.json").read_text(encoding="utf-8"))

    def test_manifest_tracks_slice_control_artifacts(self):
        build = sp.build_source_package_content(self.target, HLD, hld_source_ref="/src/HLD.md")
        manifest = json.loads((build.source_dir / sp.SOURCE_MANIFEST_FILE).read_text(encoding="utf-8"))
        filenames = {entry["filename"] for entry in manifest["files"].values()}
        self.assertIn("implementation_slices.json", filenames)
        self.assertIn("slice_test_policy.md", filenames)
        self.assertIn("speckit_slice_execution_prompt.md", filenames)


class DocumentationAndAgentInstructionTests(unittest.TestCase):
    def test_architecture_readme_exists_and_describes_specify_to_slice_flow(self):
        doc = Path("docs/HLDSPEC_ARCHITECTURE_README.md")
        self.assertTrue(doc.is_file())
        text = doc.read_text(encoding="utf-8")
        self.assertIn("One full HLD", text)
        self.assertIn("One specify, one plan, one tasks, one analyze", text)
        self.assertIn("many slice-controlled implementation passes", text)
        self.assertIn(".hldspec/source_package/", text)
        self.assertIn(".specify/source/", text)

    def test_repo_and_target_agent_instructions_include_slice_read_rule(self):
        required = "Before any SpecKit phase, read `.specify/source/HLD.md`"
        self.assertIn(required, Path("AGENTS.md").read_text(encoding="utf-8"))
        self.assertIn(required, Path("templates/orchestrator/AGENTS.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
