from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any

from hldspec.script_io import load_json_dict, select_sync_dir

MARKER_BEGIN = "<!-- HLDSPEC-AGENT-CONTEXT:BEGIN -->"
MARKER_END = "<!-- HLDSPEC-AGENT-CONTEXT:END -->"
BUILD_LOOP_HEADING = "## Build Loop"

RUNTIME_TARGET_FILES: dict[str, str] = {
    "claude": "CLAUDE.md",
    "codex": "AGENTS.md",
    "devin": ".devin/instructions.md",
}


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def _bundle_prompt_paths(workspace: Path, queue: dict[str, Any], runtime: str) -> list[str]:
    paths: list[str] = []
    for bundle in queue.get("bundles", []):
        if not isinstance(bundle, dict):
            continue
        prompt_paths = bundle.get("prompt_paths")
        if not isinstance(prompt_paths, dict):
            continue
        relpath = prompt_paths.get(runtime)
        if not relpath:
            continue
        prompt_path = workspace / str(relpath)
        if prompt_path.is_file():
            paths.append(str(Path(str(relpath))))
    return paths


def _active_runtimes(workspace: Path, queue: dict[str, Any]) -> dict[str, list[str]]:
    active: dict[str, list[str]] = {}
    for runtime in RUNTIME_TARGET_FILES:
        prompt_paths = _bundle_prompt_paths(workspace, queue, runtime)
        if prompt_paths:
            active[runtime] = prompt_paths
    return active


def _build_loop_section(runtime: str, prompt_paths: list[str], handoff_relpath: str) -> str:
    lines = [
        BUILD_LOOP_HEADING,
        "",
        f"- Runtime: `{runtime}`",
        f"- Co-located handoff: `{handoff_relpath}`",
        "- Read the handoff first, then open the runtime bundle prompts in order.",
        "- Stop on missing evidence, ACTION, CONFLICT, or a human-owned decision.",
        "- Do not move the Build Loop section inside the marker block below.",
        "",
        "Prompt paths:",
    ]
    for relpath in prompt_paths:
        lines.append(f"- `{relpath}`")
    lines += [
        "",
        MARKER_BEGIN,
        f"- runtime: `{runtime}`",
        "- purpose: agent-context handoff for Journey 3 bundle prompts",
        f"- generated by: `scripts/write_agent_context_handoff.py`",
        f"- source handoff: `{handoff_relpath}`",
        "- prompt files are runtime-specific and must exist before this section is written",
        MARKER_END,
        "",
    ]
    return "\n".join(lines)


def _insert_build_loop(existing: str, section: str) -> str:
    if BUILD_LOOP_HEADING in existing:
        return existing.rstrip() + "\n"
    if MARKER_BEGIN in existing:
        return re.sub(
            rf"\n?{re.escape(MARKER_BEGIN)}",
            "\n" + section.rstrip() + "\n\n" + MARKER_BEGIN,
            existing,
            count=1,
            flags=re.DOTALL,
        ).rstrip() + "\n"
    return existing.rstrip() + "\n\n" + section.rstrip() + "\n"


def _ensure_base_orchestrator_file(repo_root: Path, workspace: Path, runtime: str) -> tuple[bool, str]:
    target = workspace / RUNTIME_TARGET_FILES[runtime]
    if target.exists():
        return True, ""

    script = repo_root / "scripts" / "install_orchestrator_instructions.sh"
    result = subprocess.run(
        [
            "bash",
            str(script),
            "--workspace",
            str(workspace),
            "--orchestrators",
            runtime,
        ],
        cwd=repo_root,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return False, result.stderr.strip() or result.stdout.strip() or f"failed to install {runtime} orchestrator instructions"
    return target.exists(), result.stderr.strip() or result.stdout.strip()


def write_agent_context_handoff(workspace: Path) -> dict[str, Any]:
    sync = select_sync_dir(workspace, ("speckit_bundle_queue.json", "speckit_invocation_queue.json"))
    queue = load_json_dict(sync / "speckit_bundle_queue.json")
    active = _active_runtimes(workspace, queue)

    repo_root = Path(__file__).resolve().parents[1]
    results: list[dict[str, Any]] = []
    written_targets: list[str] = []
    skipped_targets: list[str] = []

    for runtime, prompt_paths in active.items():
        exists, installer_output = _ensure_base_orchestrator_file(repo_root, workspace, runtime)
        target = workspace / RUNTIME_TARGET_FILES[runtime]
        if not exists:
            results.append(
                {
                    "runtime": runtime,
                    "target": str(target),
                    "status": "ACTION",
                    "reason": "missing orchestrator file",
                }
            )
            continue

        existing = _read_text(target)
        section = _build_loop_section(runtime, prompt_paths, ".hldspec-run/hldspec-gap-agent-context-handoff.md")
        updated = _insert_build_loop(existing, section)
        if updated == existing.rstrip() + "\n":
            skipped_targets.append(str(target))
            results.append(
                {
                    "runtime": runtime,
                    "target": str(target),
                    "status": "SKIPPED",
                    "reason": "build loop section already present",
                }
            )
            continue

        _write_text(target, updated)
        written_targets.append(str(target))
        results.append(
            {
                "runtime": runtime,
                "target": str(target),
                "status": "WRITTEN",
                "prompt_paths": prompt_paths,
                "installer_output": installer_output,
            }
        )

    run_dir = workspace / ".hldspec-run"
    run_dir.mkdir(parents=True, exist_ok=True)
    handoff_path = run_dir / "hldspec-gap-agent-context-handoff.md"
    handoff_path.write_text(render_handoff_markdown(workspace, queue, active, results), encoding="utf-8")

    status = "PASS"
    if not active:
        status = "ACTION"
    elif any(item.get("status") == "ACTION" for item in results):
        status = "ACTION"

    return {
        "status": status,
        "workspace": str(workspace),
        "handoff_path": str(handoff_path),
        "active_runtimes": sorted(active.keys()),
        "written_targets": written_targets,
        "skipped_targets": skipped_targets,
        "results": results,
    }


def render_handoff_markdown(
    workspace: Path,
    queue: dict[str, Any],
    active: dict[str, list[str]],
    results: list[dict[str, Any]],
) -> str:
    lines = [
        "# HLDspec Agent Context Handoff",
        "",
        "## Current state",
        "",
        f"- workspace: `{workspace}`",
        f"- bundle queue: `{workspace / '.specify' / 'sync' / 'speckit_bundle_queue.json'}`",
        f"- run dir: `{workspace / '.hldspec-run'}`",
        f"- active runtimes: {', '.join(f'`{runtime}`' for runtime in sorted(active.keys())) or 'none'}",
        "",
        "## Problem",
        "",
        "Prework finishes and bundle prompts exist, but no agent context handoff is written. Journey 3 can see prompts, but the maintainer has no colocated run-dir artifact that explains what was written and which runtime files were updated.",
        "",
        "## Root cause",
        "",
        "There is no dedicated post-bundle step in the pipeline that writes a runtime-facing agent context handoff after `build_speckit_bundle_prompts.py` completes.",
        "",
        "## Required change",
        "",
        "Add one post-bundle step that writes the runtime-specific root files only when actual prompts exist for that runtime:",
        "",
        f"- `{RUNTIME_TARGET_FILES['claude']}` for Claude prompts",
        f"- `{RUNTIME_TARGET_FILES['codex']}` for Codex prompts",
        f"- `{RUNTIME_TARGET_FILES['devin']}` for Devin prompts",
        "",
        "## Idempotency",
        "",
        "Safe to rerun. If the Build Loop section already exists, the writer skips that file instead of duplicating the section.",
        "",
        "## SPECKIT zone protection",
        "",
        "The Build Loop section must sit above the marker block and never inside it.",
        "",
        "## Acceptance criteria",
        "",
        "- [ ] Bundle prompts exist before the handoff step runs.",
        "- [ ] Only runtimes with actual prompt files get a root-context update.",
        "- [ ] Build Loop appears exactly once in each written runtime file.",
        "- [ ] The Build Loop section is placed above the marker block.",
        "- [ ] Rerunning the step does not duplicate the Build Loop section.",
        "- [ ] Runtime files without actual prompts are left untouched.",
        "- [ ] The run-dir handoff file is written beside the HLDspec run artifacts.",
        "",
        "## Secondary gap",
        "",
        "The `spec_build_plan.md` `Next safe steps` section is too generic. It should name the concrete follow-up: review the plan, generate bundle prompts, then run the new agent-context handoff step before any SpecKit handoff.",
        "",
        "## Build Loop",
        "",
        "1. Read this handoff first.",
        "2. Open the runtime-specific root file for the active prompt surface.",
        "3. Follow the bundle prompts in order.",
        "4. Stop on missing evidence, ACTION, CONFLICT, or a human-owned decision.",
        "5. Report files changed, tests run, RunSkeptic status, and the next safe action.",
        "",
        "## Results",
        "",
    ]
    for item in results:
        runtime = item.get("runtime", "")
        target = item.get("target", "")
        status = item.get("status", "")
        lines += [
            f"- `{runtime}` -> `{status}` -> `{target}`",
        ]
    lines += [
        "",
        "## Evidence",
        "",
        f"- queue bundles: `{len(queue.get('bundles', [])) if isinstance(queue.get('bundles'), list) else 0}`",
        f"- active runtimes: {', '.join(sorted(active.keys())) or 'none'}",
        "",
    ]
    return "\n".join(lines)
