"""HLD source package — the single-HLD SpecKit source-package architecture.

Ownership model (resolved 2026-05-27, see
docs/archive/REWRITE_PROMPT_RUNSKEPTIC_REVIEW_2026-05-27.md):

- HLDspec *authors* the approved source package under the resolved control plane,
  ``control_state_root/source_package/``. In default/no-pointer mode this resolves
  to ``target/.hldspec/source_package/``; in external-controller mode it resolves
  to ``controller_root/.hldspec/source_package/``.
- A *derived, read-only mirror* is materialised under ``target/.specify/source/``
  for the SpecKit runner. The mirror is generated, never hand-authored, so the
  canonical invariant "HLDspec never authors into .specify/" still holds.
- The constitution is authored here only as a *proposal*
  (``control_state_root/source_package/constitution.proposed.md``); it is applied
  to ``.specify/memory/`` only at CONSTITUTION_APPROVAL_GATE, not by this module.

This module owns the *container*: the file contract, the manifest (with hashes),
``source_package.json`` metadata, validation, and mirror materialisation. The
*content* of marked HLD, single-spec input, guidelines, runbook, prompts, etc. is
produced by later slices.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

from . import agent_handoff_pack, control_paths, helper_registry, journey2_architecture_package
from .script_io import load_json_dict, write_json_dict
from .spec_bundles import utc_now
from .workspace_adapter import TargetWorkspaceAdapter

SCHEMA_VERSION = 1

# Target/source binding (invariant B): a source package generated for one
# target/source must not transfer trust when copied elsewhere. The binding is
# stamped into source_package.json at build time and verified by discovery.
BINDING_SCHEMA_VERSION = 1
BINDING_CREATED_BY = "HLDspec"
BINDING_FIELDS: tuple[str, ...] = ("binding_schema_version", "target_path", "target_path_sha256")

# Generated-file banner stamped on every mirrored file so a reader (or a human
# inspecting .specify/source/) can tell it is derived and must not be edited.
GENERATED_BANNER = (
    "<!-- GENERATED by HLDspec — derived read-only mirror of "
    ".hldspec/source_package/. Do not edit; edit the source package and "
    "re-materialise. -->"
)

# Logical name -> filename within the source-package directory.
# These are the files HLDspec authors. Content generation is per-slice; this
# module only knows the contract.
AUTHORITATIVE_FILES: dict[str, str] = {
    "hld": "HLD.md",
    "marked_hld": "HLD.marked.md",
    "reference_map": "hld_reference_map.json",
    "engineering_guidelines": "engineering_guidelines.md",
    "single_spec_input": "speckit_single_spec_input.md",
    "runbook": "speckit_runbook.md",
    "runner_prompt": "runner_prompt.md",
    "consultant_prompt": "consultant_prompt.md",
    "human_review_package": "human_review_package.md",
    "implementation_slicing_policy": "implementation_slicing_policy.md",
    "implementation_slices": "implementation_slices.json",
    "slice_test_policy": "slice_test_policy.md",
    "speckit_slice_execution_prompt": "speckit_slice_execution_prompt.md",
    "anchor_coverage_schema": "anchor_coverage_schema.json",
    # Journey 2 → Journey 3 advisory seam. Not in REQUIRED_FILES (advisory) and
    # not in MIRROR_FILES (J3 guidance, not SpecKit runner content). It is in
    # AUTHORITATIVE_FILES so the manifest hashes it and drift is detectable.
    "helper_recommendations": "helper_recommendations.json",
    # Journey 2 architecture-design slot (advisory). Same treatment as
    # helper_recommendations: hashed for drift, never mirrored, never required.
    # Emitted as an honest ACTION typed slot until a human authors its fields
    # (see journey2_architecture_package.build_architecture_package).
    "architecture_package": "architecture_package.json",
}

# Authored here but NOT mirrored into .specify/source/: the constitution is a
# proposal applied separately at the approval gate.
CONSTITUTION_PROPOSAL_FILE = "constitution.proposed.md"

# Index files (computed, not part of the hashed content set).
SOURCE_MANIFEST_FILE = "source_manifest.json"
SOURCE_PACKAGE_FILE = "source_package.json"

# Advisory files that live in the source package but must not travel into the
# SpecKit runner mirror (.specify/source/). Listed explicitly so that adding a
# new advisory file to AUTHORITATIVE_FILES does not silently mirror it.
_MIRROR_EXCLUDED: frozenset[str] = frozenset({
    # J3 advisory guidance — not SpecKit runner content.
    AUTHORITATIVE_FILES["helper_recommendations"],
    # J2 architecture-design slot — advisory, not SpecKit runner content.
    AUTHORITATIVE_FILES["architecture_package"],
})

# The subset materialised into .specify/source/ for the runner. The constitution
# proposal and the package metadata file are intentionally excluded; the manifest
# and reference map travel with the mirror so the runner can verify it.
MIRROR_FILES: tuple[str, ...] = tuple(
    f for f in AUTHORITATIVE_FILES.values() if f not in _MIRROR_EXCLUDED
) + (SOURCE_MANIFEST_FILE,)

# Every filename HLDspec may ever place or manage inside the mirror. The mirror is
# wiped of these (and only these) before re-materialising, so an orphan left by a
# dropped source file cannot persist, while non-HLDspec content in .specify/source/
# is never touched.
HLDSPEC_MANAGED_MIRROR_NAMES: frozenset[str] = frozenset(
    set(AUTHORITATIVE_FILES.values())
    | {SOURCE_MANIFEST_FILE, SOURCE_PACKAGE_FILE, CONSTITUTION_PROPOSAL_FILE}
)

# Files whose presence is required for a complete source package. Slice 1 keeps
# this minimal; later slices that generate more content tighten it.
REQUIRED_FILES: tuple[str, ...] = (
    AUTHORITATIVE_FILES["hld"],
    AUTHORITATIVE_FILES["marked_hld"],
    AUTHORITATIVE_FILES["reference_map"],
    AUTHORITATIVE_FILES["single_spec_input"],
    AUTHORITATIVE_FILES["engineering_guidelines"],
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalized_target_path(target_root: Path) -> str:
    """The exact target-path string the binding records and hashes."""
    return str(Path(target_root).expanduser().resolve())


def path_sha256(path_str: str) -> str:
    return hashlib.sha256(path_str.encode("utf-8")).hexdigest()


def build_binding_fields(
    target_root: Path,
    *,
    source_ref: str,
    source_sha256: str | None = None,
) -> dict:
    """Binding metadata for source_package.json.

    `target_path_sha256` hashes the recorded `target_path` string itself so a
    hand-edited or truncated binding is detectable as malformed, independent of
    whether the recorded path happens to resolve.
    """
    target_path = normalized_target_path(target_root)
    return {
        "created_by": BINDING_CREATED_BY,
        "created_at": utc_now(),
        "binding_schema_version": BINDING_SCHEMA_VERSION,
        "target_path": target_path,
        "target_path_sha256": path_sha256(target_path),
        "source_ref": source_ref,
        "source_sha256": source_sha256,
    }


def _source_file_sha256(ref: str) -> str | None:
    """Hash the source HLD file content when the ref is an existing file."""
    try:
        path = Path(ref).expanduser()
        if path.is_file():
            return _sha256(path)
    except OSError:
        return None
    return None


@dataclass(frozen=True)
class ManifestEntry:
    name: str
    filename: str
    present: bool
    sha256: str | None


@dataclass
class SourcePackageValidation:
    missing: list[str] = field(default_factory=list)
    hash_mismatches: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.missing and not self.hash_mismatches


def compute_manifest(source_dir: Path) -> dict[str, dict]:
    """Hash every authoritative content file. Index files are excluded so the
    manifest never tries to hash itself."""
    entries: dict[str, dict] = {}
    named = dict(AUTHORITATIVE_FILES)
    named["constitution_proposal"] = CONSTITUTION_PROPOSAL_FILE
    for name, filename in named.items():
        path = source_dir / filename
        present = path.is_file()
        entries[name] = {
            "filename": filename,
            "present": present,
            "sha256": _sha256(path) if present else None,
        }
    return entries


def write_source_manifest(source_dir: Path) -> dict[str, dict]:
    manifest = compute_manifest(source_dir)
    write_json_dict(source_dir / SOURCE_MANIFEST_FILE, {
        "schema_version": SCHEMA_VERSION,
        "files": manifest,
    })
    return manifest


def build_source_package_metadata(
    *,
    hld_source_ref: str,
    state: str,
    manifest: dict[str, dict],
    binding: dict | None = None,
) -> dict:
    metadata = {
        "schema_version": SCHEMA_VERSION,
        "hld_source_ref": hld_source_ref,
        "state": state,
        "manifest_file": SOURCE_MANIFEST_FILE,
        "mirror_files": list(MIRROR_FILES),
        "required_files": list(REQUIRED_FILES),
        "file_count": len(manifest),
    }
    if binding:
        metadata.update(binding)
    return metadata


def write_source_package(
    source_dir: Path,
    *,
    hld_source_ref: str,
    state: str,
    target_root: Path | None = None,
    source_sha256: str | None = None,
) -> dict:
    """Write source_manifest.json then source_package.json. Returns the metadata.

    When `target_root` is given the metadata carries target/source binding
    fields; discovery only trusts a bound package whose binding matches. A
    call without `target_root` writes an unbound (legacy-shaped) package that
    discovery reports as UNBOUND_LEGACY and never fully trusts.
    """
    manifest = write_source_manifest(source_dir)
    binding = (
        build_binding_fields(target_root, source_ref=hld_source_ref, source_sha256=source_sha256)
        if target_root is not None
        else None
    )
    metadata = build_source_package_metadata(
        hld_source_ref=hld_source_ref, state=state, manifest=manifest, binding=binding
    )
    write_json_dict(source_dir / SOURCE_PACKAGE_FILE, metadata)
    return metadata


def validate_source_package(source_dir: Path) -> SourcePackageValidation:
    """Check required files are present and that any recorded manifest hashes
    still match the files on disk."""
    result = SourcePackageValidation()
    for filename in REQUIRED_FILES:
        if not (source_dir / filename).is_file():
            result.missing.append(filename)

    recorded = load_json_dict(source_dir / SOURCE_MANIFEST_FILE).get("files", {})
    for name, entry in recorded.items():
        filename = entry.get("filename")
        recorded_hash = entry.get("sha256")
        if not filename or recorded_hash is None:
            continue
        path = source_dir / filename
        if not path.is_file():
            result.missing.append(filename)
        elif _sha256(path) != recorded_hash:
            result.hash_mismatches.append(filename)
    return result


def materialize_specify_mirror(
    source_dir: Path,
    mirror_dir: Path,
) -> list[str]:
    """Regenerate the derived read-only mirror under .specify/source/.

    Idempotent and orphan-free: every HLDspec-managed name is removed first, then
    the current mirror set is rewritten, so a file dropped from the source package
    (or the constitution proposal) cannot persist in the mirror. Non-HLDspec
    content in the mirror directory is never touched. Markdown files get a
    GENERATED banner. Returns the list of mirrored filenames.
    """
    mirror_dir.mkdir(parents=True, exist_ok=True)
    # Wipe only HLDspec-managed names so orphans cannot survive a regeneration.
    for name in HLDSPEC_MANAGED_MIRROR_NAMES:
        stale = mirror_dir / name
        if stale.exists():
            stale.unlink()
    written: list[str] = []
    for filename in MIRROR_FILES:
        src = source_dir / filename
        if not src.is_file():
            continue
        dest = mirror_dir / filename
        data = src.read_text(encoding="utf-8")
        if filename.endswith(".md"):
            data = f"{GENERATED_BANNER}\n\n{data}"
        dest.write_text(data, encoding="utf-8")
        written.append(filename)
    return written


def source_package_paths(target_root: Path, layout: str = "new") -> tuple[Path, Path]:
    """The single pointer-aware resolver for (authoritative source dir, mirror dir).

    Pointer-aware (Option C): when a valid ``.hldspec-run.json`` pointer names an
    external controller root, the *authoritative* source package resolves under the
    controller (the externalized HLDspec control plane). The mirror always stays at
    the target's ``.specify/source/`` because it is the delivered, in-target SpecKit
    runtime. Without a pointer this is byte-identical to legacy in-target resolution.

    Both the Journey 3 driver (read) and ``build_source_package_content`` (write)
    resolve through here, so read and write can never disagree on the location.
    """
    adapter = TargetWorkspaceAdapter(
        target_root=target_root,
        layout=layout,
        controller_root=control_paths.resolve_controller_root(target_root),
    )
    return adapter.source_package_dir, adapter.specify_source_mirror_dir


def source_package_split_brain(target_root: Path) -> Path | None:
    """Detect a source-package split-brain; return the conflicting in-target dir, else None.

    A completed externalization deletes the in-target ``.hldspec/`` entirely
    (``run_state.externalize_target_control_artifacts``), so a healthy external
    target never holds an in-target ``source_package.json``. When external mode is
    active AND an authoritative package exists in BOTH the controller and the
    target, ownership is ambiguous (interrupted externalization, or a manual
    in-target build). The caller must fail closed rather than silently pick one or
    repair — this only reports the conflict; it never deletes or reconciles.
    """
    controller = control_paths.resolve_controller_root(target_root)
    if controller is None:
        return None  # normal mode: in-target IS the single authoritative location.
    controller_pkg = controller / ".hldspec" / "source_package" / SOURCE_PACKAGE_FILE
    in_target = Path(target_root) / ".hldspec" / "source_package"
    if controller_pkg.is_file() and (in_target / SOURCE_PACKAGE_FILE).is_file():
        return in_target
    return None


@dataclass
class SourcePackageBuild:
    source_dir: Path
    anchor_count: int
    unsupported_claims: list[str]
    validation: "SourcePackageValidation"
    mirrored: list[str]
    marking_errors: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.validation.ok and not self.unsupported_claims and not self.marking_errors


# Advisory, package-fit-only context per implemented helper. Capability facts
# (status, authority levels) are NOT stored here — they are derived from the
# helper registry at build time. Only this fit explanation is Journey-2-owned.
_HELPER_PACKAGE_FIT: dict[str, dict] = {
    "speckit": {
        "package_fit": "high",
        "target_fit": "requires a SpecKit-initialized target repo",
        "rationale": (
            "This package is a single anchored spec input plus engineering "
            "guidelines and implementation slices — the shape SpecKit's "
            "specify→plan→tasks→implement ritual consumes natively."
        ),
    },
}


def build_helper_recommendations(registry: dict | None = None) -> dict:
    """Advisory Journey 2 output: which helper is recommended for THIS package, and why.

    Helper capability facts (helper_id, status, authority levels) are **derived**
    from `hldspec/helper_registry.py` — the canonical source of truth for helper
    capabilities. This file is not a copy of the registry; it adds only advisory
    package-fit information. The not-implemented helper IDs come from the registry's
    `PLANNED_HELPER_IDS`, not an independent list here.

    It does NOT record which helper the targeteer selected
    (`.hldspec/helper_selection.json`, a future Journey 3 slice), an execution
    prompt (NextActionPacket), or unresolved questions (inquiry/gap ledger).
    """
    reg = helper_registry.build_registry() if registry is None else registry

    recommended = []
    for helper in helper_registry.implemented_helpers(reg):
        helper_id = helper["helper_id"]
        fit = _HELPER_PACKAGE_FIT.get(helper_id, {})
        recommended.append({
            "helper_id": helper_id,
            "status": helper["status"],                            # derived from registry
            "authority_levels": list(helper["authority_levels"]),  # derived from registry
            "package_fit": fit.get("package_fit", "unknown"),      # advisory (Journey 2)
            "target_fit": fit.get("target_fit", "unknown"),        # advisory (Journey 2)
            "rationale": fit.get("rationale", ""),                 # advisory (Journey 2)
        })

    unsupported = [
        {
            "helper_id": helper_id,
            "status": "not_implemented",
            "reason": (
                "Contracted in docs/JOURNEY3_HELPER_CONTRACT.md / "
                "docs/HELPER_BOOTSTRAP_CONTRACT.md but not yet an operational helper "
                "in the helper registry."
            ),
        }
        for helper_id in helper_registry.PLANNED_HELPER_IDS
    ]

    return {
        "schema_version": 1,
        "default_helper": helper_registry.default_helper_id(reg),  # derived from registry
        "registry_provenance": {
            "schema_version": reg.get("schema_version"),
            "registry_sha256": helper_registry.registry_sha256(reg),
        },
        "recommended_helpers": recommended,
        "unsupported_helpers": unsupported,
        "required_capabilities": [
            "spec-driven implementation guidance over an anchored source package",
        ],
        "human_override_allowed": True,
        "notes": [
            "Advisory Journey 2 output. Helper capability facts are derived from "
            "hldspec/helper_registry.py; this file is not a copy of the registry.",
            "Records which helper is recommended for this package, not which helper "
            "was selected. Selection is .hldspec/helper_selection.json (future).",
            "Regenerate after structural HLD changes or after the helper registry changes.",
        ],
    }


def build_source_package_content(
    target_root: Path,
    hld_text: str,
    *,
    hld_source_ref: str,
    state: str = "SOURCE_PACKAGE_IMPORTED",
    project_name: str = "",
    layout: str = "new",
    materialize_mirror: bool = True,
    source_sha256: str | None = None,
) -> SourcePackageBuild:
    """Real content flow: turn an HLD into the full source-package content.

    Writes HLD.md, HLD.marked.md, hld_reference_map.json,
    speckit_single_spec_input.md, then the manifest + metadata, then optionally
    regenerates the .specify/source/ mirror. Returns a structured build result
    (does not raise on content findings — unsupported claims surface for the
    gate, matching the SourcePackageValidation pattern).
    """
    # Imported here to avoid an import cycle (those modules import this one).
    from . import hld_marking, single_spec_input, implementation_slicing, engineering_selection

    # Resolve through the single pointer-aware resolver so write lands where the
    # driver reads (controller root in external mode, in-target otherwise).
    source_dir, mirror_dir = source_package_paths(target_root, layout=layout)
    source_dir.mkdir(parents=True, exist_ok=True)

    (source_dir / AUTHORITATIVE_FILES["hld"]).write_text(hld_text, encoding="utf-8")
    (source_dir / AUTHORITATIVE_FILES["marked_hld"]).write_text(
        hld_marking.build_marked_hld(hld_text), encoding="utf-8"
    )
    ref_map = hld_marking.build_reference_map(hld_text)
    write_json_dict(source_dir / AUTHORITATIVE_FILES["reference_map"], ref_map)

    spec_input = single_spec_input.build_single_spec_input(hld_text, project_name=project_name)
    (source_dir / AUTHORITATIVE_FILES["single_spec_input"]).write_text(spec_input, encoding="utf-8")

    for filename, content in implementation_slicing.build_implementation_slicing_artifacts().items():
        (source_dir / filename).write_text(content, encoding="utf-8")

    (source_dir / AUTHORITATIVE_FILES["engineering_guidelines"]).write_text(
        engineering_selection.render_engineering_guidelines_md(hld_text, project_name=project_name),
        encoding="utf-8",
    )

    helper_recommendations = build_helper_recommendations()
    write_json_dict(
        source_dir / AUTHORITATIVE_FILES["helper_recommendations"],
        helper_recommendations,
    )
    # Advisory Journey 2 architecture slot. Grounds only helper_recommendation
    # (registry-derived); the human-owned fields are emitted empty so the artifact
    # honestly validates ACTION until authored. Never required, never mirrored.
    write_json_dict(
        source_dir / AUTHORITATIVE_FILES["architecture_package"],
        journey2_architecture_package.build_architecture_package(
            helper_recommendation=helper_recommendations,
        ),
    )

    valid_anchors = set(ref_map["anchors"].keys())
    unsupported = single_spec_input.find_unsupported_claims(spec_input, valid_anchors)
    marking_errors = hld_marking.anchor_integrity_errors(hld_text)

    write_source_package(
        source_dir,
        hld_source_ref=hld_source_ref,
        state=state,
        target_root=target_root,
        source_sha256=source_sha256 or _source_file_sha256(hld_source_ref),
    )
    validation = validate_source_package(source_dir)
    mirrored: list[str] = []
    if materialize_mirror:
        mirrored = materialize_specify_mirror(source_dir, mirror_dir)

    try:
        agent_handoff_pack.write_agent_handoff_pack_artifacts(target_root)
    except Exception as exc:
        raise RuntimeError(
            f"failed to write Journey 3 Agent Handoff Pack artifacts under {target_root}: {exc}"
        ) from exc

    return SourcePackageBuild(
        source_dir=source_dir,
        anchor_count=len(valid_anchors),
        unsupported_claims=unsupported,
        validation=validation,
        mirrored=mirrored,
        marking_errors=marking_errors,
    )
