"""HLD source package — the single-HLD SpecKit source-package architecture.

Ownership model (resolved 2026-05-27, see
docs/archive/REWRITE_PROMPT_RUNSKEPTIC_REVIEW_2026-05-27.md):

- HLDspec *authors* the approved source package under
  ``target/.hldspec/source_package/`` (the control plane).
- A *derived, read-only mirror* is materialised under ``target/.specify/source/``
  for the SpecKit runner. The mirror is generated, never hand-authored, so the
  canonical invariant "HLDspec never authors into .specify/" still holds.
- The constitution is authored here only as a *proposal*
  (``constitution.proposed.md``); it is applied to ``.specify/memory/`` at the
  CONSTITUTION_APPROVAL_GATE, not by this module.

This module owns the *container*: the file contract, the manifest (with hashes),
``source_package.json`` metadata, validation, and mirror materialisation. The
*content* of marked HLD, single-spec input, guidelines, runbook, prompts, etc. is
produced by later slices.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

from . import mediator_guidance
from .script_io import load_json_dict, write_json_dict
from .spec_bundles import utc_now
from .workspace_adapter import TargetWorkspaceAdapter

SCHEMA_VERSION = 1

# Target/source binding (invariant B): a source package generated for one
# target/source must not transfer trust when copied elsewhere. The binding is
# stamped into source_package.json at build time and verified by discovery.
BINDING_SCHEMA_VERSION = 1
BINDING_CREATED_BY = "HLDspec"
BINDING_FIELDS: tuple[str, ...] = ("binding_schema_version", "target_path", "target_path_sha256")

# Generated-file banner stamped on every mirrored file so a reader (or a human
# inspecting .specify/source/) can tell it is derived and must not be edited.
GENERATED_BANNER = (
    "<!-- GENERATED by HLDspec — derived read-only mirror of "
    ".hldspec/source_package/. Do not edit; edit the source package and "
    "re-materialise. -->"
)

# Logical name -> filename within the source-package directory.
# These are the files HLDspec authors. Content generation is per-slice; this
# module only knows the contract.
AUTHORITATIVE_FILES: dict[str, str] = {
    "hld": "HLD.md",
    "marked_hld": "HLD.marked.md",
    "reference_map": "hld_reference_map.json",
    "engineering_guidelines": "engineering_guidelines.md",
    "single_spec_input": "speckit_single_spec_input.md",
    "runbook": "speckit_runbook.md",
    "runner_prompt": "runner_prompt.md",
    "consultant_prompt": "consultant_prompt.md",
    "human_review_package": "human_review_package.md",
    "implementation_slicing_policy": "implementation_slicing_policy.md",
    "implementation_slices": "implementation_slices.json",
    "slice_test_policy": "slice_test_policy.md",
    "speckit_slice_execution_prompt": "speckit_slice_execution_prompt.md",
    "anchor_coverage_schema": "anchor_coverage_schema.json",
    # Journey 2 → Journey 3 advisory seam. Not in REQUIRED_FILES (advisory) and
    # not in MIRROR_FILES (J3 guidance, not SpecKit runner content). It is in
    # AUTHORITATIVE_FILES so the manifest hashes it and drift is detectable.
    "helper_recommendations": "helper_recommendations.json",
}

# Authored here but NOT mirrored into .specify/source/: the constitution is a
# proposal applied separately at the approval gate.
CONSTITUTION_PROPOSAL_FILE = "constitution.proposed.md"

# Index files (computed, not part of the hashed content set).
SOURCE_MANIFEST_FILE = "source_manifest.json"
SOURCE_PACKAGE_FILE = "source_package.json"

# Advisory files that live in the source package but must not travel into the
# SpecKit runner mirror (.specify/source/). Listed explicitly so that adding a
# new advisory file to AUTHORITATIVE_FILES does not silently mirror it.
_MIRROR_EXCLUDED: frozenset[str] = frozenset({
    # J3 advisory guidance — not SpecKit runner content.
    AUTHORITATIVE_FILES["helper_recommendations"],
})

# The subset materialised into .specify/source/ for the runner. The constitution
# proposal and the package metadata file are intentionally excluded; the manifest
# and reference map travel with the mirror so the runner can verify it.
MIRROR_FILES: tuple[str, ...] = tuple(
    f for f in AUTHORITATIVE_FILES.values() if f not in _MIRROR_EXCLUDED
) + (SOURCE_MANIFEST_FILE,)

# Every filename HLDspec may ever place or manage inside the mirror. The mirror is
# wiped of these (and only these) before re-materialising, so an orphan left by a
# dropped source file cannot persist, while non-HLDspec content in .specify/source/
# is never touched.
HLDSPEC_MANAGED_MIRROR_NAMES: frozenset[str] = frozenset(
    set(AUTHORITATIVE_FILES.values())
    | {SOURCE_MANIFEST_FILE, SOURCE_PACKAGE_FILE, CONSTITUTION_PROPOSAL_FILE}
)

# Files whose presence is required for a complete source package. Slice 1 keeps
# this minimal; later slices that generate more content tighten it.
REQUIRED_FILES: tuple[str, ...] = (
    AUTHORITATIVE_FILES["hld"],
    AUTHORITATIVE_FILES["marked_hld"],
    AUTHORITATIVE_FILES["reference_map"],
    AUTHORITATIVE_FILES["single_spec_input"],
    AUTHORITATIVE_FILES["engineering_guidelines"],
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalized_target_path(target_root: Path) -> str:
    """The exact target-path string the binding records and hashes."""
    return str(Path(target_root).expanduser().resolve())


def path_sha256(path_str: str) -> str:
    return hashlib.sha256(path_str.encode("utf-8")).hexdigest()


def build_binding_fields(
    target_root: Path,
    *,
    source_ref: str,
    source_sha256: str | None = None,
) -> dict:
    """Binding metadata for source_package.json.

    `target_path_sha256` hashes the recorded `target_path` string itself so a
    hand-edited or truncated binding is detectable as malformed, independent of
    whether the recorded path happens to resolve.
    """
    target_path = normalized_target_path(target_root)
    return {
        "created_by": BINDING_CREATED_BY,
        "created_at": utc_now(),
        "binding_schema_version": BINDING_SCHEMA_VERSION,
        "target_path": target_path,
        "target_path_sha256": path_sha256(target_path),
        "source_ref": source_ref,
        "source_sha256": source_sha256,
    }


def _source_file_sha256(ref: str) -> str | None:
    """Hash the source HLD file content when the ref is an existing file."""
    try:
        path = Path(ref).expanduser()
        if path.is_file():
            return _sha256(path)
    except OSError:
        return None
    return None


@dataclass(frozen=True)
class ManifestEntry:
    name: str
    filename: str
    present: bool
    sha256: str | None


@dataclass
class SourcePackageValidation:
    missing: list[str] = field(default_factory=list)
    hash_mismatches: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.missing and not self.hash_mismatches


def compute_manifest(source_dir: Path) -> dict[str, dict]:
    """Hash every authoritative content file. Index files are excluded so the
    manifest never tries to hash itself."""
    entries: dict[str, dict] = {}
    named = dict(AUTHORITATIVE_FILES)
    named["constitution_proposal"] = CONSTITUTION_PROPOSAL_FILE
    for name, filename in named.items():
        path = source_dir / filename
        present = path.is_file()
        entries[name] = {
            "filename": filename,
            "present": present,
            "sha256": _sha256(path) if present else None,
        }
    return entries


def write_source_manifest(source_dir: Path) -> dict[str, dict]:
    manifest = compute_manifest(source_dir)
    write_json_dict(source_dir / SOURCE_MANIFEST_FILE, {
        "schema_version": SCHEMA_VERSION,
        "files": manifest,
    })
    return manifest


def build_source_package_metadata(
    *,
    hld_source_ref: str,
    state: str,
    manifest: dict[str, dict],
    binding: dict | None = None,
) -> dict:
    metadata = {
        "schema_version": SCHEMA_VERSION,
        "hld_source_ref": hld_source_ref,
        "state": state,
        "manifest_file": SOURCE_MANIFEST_FILE,
        "mirror_files": list(MIRROR_FILES),
        "required_files": list(REQUIRED_FILES),
        "file_count": len(manifest),
    }
    if binding:
        metadata.update(binding)
    return metadata


def write_source_package(
    source_dir: Path,
    *,
    hld_source_ref: str,
    state: str,
    target_root: Path | None = None,
    source_sha256: str | None = None,
) -> dict:
    """Write source_manifest.json then source_package.json. Returns the metadata.

    When `target_root` is given the metadata carries target/source binding
    fields; discovery only trusts a bound package whose binding matches. A
    call without `target_root` writes an unbound (legacy-shaped) package that
    discovery reports as UNBOUND_LEGACY and never fully trusts.
    """
    manifest = write_source_manifest(source_dir)
    binding = (
        build_binding_fields(target_root, source_ref=hld_source_ref, source_sha256=source_sha256)
        if target_root is not None
        else None
    )
    metadata = build_source_package_metadata(
        hld_source_ref=hld_source_ref, state=state, manifest=manifest, binding=binding
    )
    write_json_dict(source_dir / SOURCE_PACKAGE_FILE, metadata)
    return metadata


def validate_source_package(source_dir: Path) -> SourcePackageValidation:
    """Check required files are present and that any recorded manifest hashes
    still match the files on disk."""
    result = SourcePackageValidation()
    for filename in REQUIRED_FILES:
        if not (source_dir / filename).is_file():
            result.missing.append(filename)

    recorded = load_json_dict(source_dir / SOURCE_MANIFEST_FILE).get("files", {})
    for name, entry in recorded.items():
        filename = entry.get("filename")
        recorded_hash = entry.get("sha256")
        if not filename or recorded_hash is None:
            continue
        path = source_dir / filename
        if not path.is_file():
            result.missing.append(filename)
        elif _sha256(path) != recorded_hash:
            result.hash_mismatches.append(filename)
    return result


def materialize_specify_mirror(
    source_dir: Path,
    mirror_dir: Path,
) -> list[str]:
    """Regenerate the derived read-only mirror under .specify/source/.

    Idempotent and orphan-free: every HLDspec-managed name is removed first, then
    the current mirror set is rewritten, so a file dropped from the source package
    (or the constitution proposal) cannot persist in the mirror. Non-HLDspec
    content in the mirror directory is never touched. Markdown files get a
    GENERATED banner. Returns the list of mirrored filenames.
    """
    mirror_dir.mkdir(parents=True, exist_ok=True)
    # Wipe only HLDspec-managed names so orphans cannot survive a regeneration.
    for name in HLDSPEC_MANAGED_MIRROR_NAMES:
        stale = mirror_dir / name
        if stale.exists():
            stale.unlink()
    written: list[str] = []
    for filename in MIRROR_FILES:
        src = source_dir / filename
        if not src.is_file():
            continue
        dest = mirror_dir / filename
        data = src.read_text(encoding="utf-8")
        if filename.endswith(".md"):
            data = f"{GENERATED_BANNER}\n\n{data}"
        dest.write_text(data, encoding="utf-8")
        written.append(filename)
    return written


def source_package_paths(target_root: Path, layout: str = "new") -> tuple[Path, Path]:
    """Convenience: (authoritative source dir, derived mirror dir)."""
    adapter = TargetWorkspaceAdapter(target_root=target_root, layout=layout)
    return adapter.source_package_dir, adapter.specify_source_mirror_dir


@dataclass
class SourcePackageBuild:
    source_dir: Path
    anchor_count: int
    unsupported_claims: list[str]
    validation: "SourcePackageValidation"
    mirrored: list[str]
    marking_errors: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.validation.ok and not self.unsupported_claims and not self.marking_errors


def build_helper_recommendations() -> dict:
    """Advisory Journey 2 output: which helpers are available for this package.

    The selected helper is recorded separately in .hldspec/helper_selection.json
    (Journey 3 state); this file describes what Journey 2 recommends. It is
    intentionally static today — speckit is the only implemented helper and the
    default. Future helpers are listed as not_implemented so Journey 3 never
    mistakes them for working.
    """
    return {
        "schema_version": 1,
        "default_helper": "speckit",
        "recommended_helpers": [
            {
                "helper_id": "speckit",
                "status": "implemented",
                "rationale": (
                    "SpecKit provides the canonical specify→clarify→plan→tasks→"
                    "analyze→implement ritual for a structured HLD source package. "
                    "The Journey 3 run-card runtime (next_feature_readiness) reads "
                    "this package natively."
                ),
                "required_capabilities": [
                    "speckit_single_spec_input.md",
                    "engineering_guidelines.md",
                    "implementation_slices.json",
                ],
                "package_fit": "high",
                "target_fit": "high — requires a SpecKit-initialized target repo",
                "authority_levels": ["GUIDE_ONLY", "PROPOSE_COMMAND"],
            }
        ],
        "unsupported_helpers": [
            {
                "helper_id": "claude-code",
                "status": "not_implemented",
                "reason": (
                    "Helper contract exists (docs/JOURNEY3_HELPER_CONTRACT.md), "
                    "but no target-local helper implementation exists yet."
                ),
            },
            {
                "helper_id": "codex",
                "status": "not_implemented",
                "reason": (
                    "Helper contract exists (docs/JOURNEY3_HELPER_CONTRACT.md), "
                    "but no target-local helper implementation exists yet."
                ),
            },
            {
                "helper_id": "devin",
                "status": "not_implemented",
                "reason": (
                    "Helper contract exists (docs/JOURNEY3_HELPER_CONTRACT.md), "
                    "but no target-local helper implementation exists yet."
                ),
            },
            {
                "helper_id": "manual",
                "status": "not_implemented",
                "reason": (
                    "Helper contract exists (docs/JOURNEY3_HELPER_CONTRACT.md), "
                    "but no target-local helper implementation exists yet."
                ),
            },
        ],
        "human_override_allowed": True,
        "notes": [
            "Advisory Journey 2 output. Records which helpers are available for this package.",
            "Journey 3 reads this file to determine the default helper. The selected helper "
            "is recorded separately in .hldspec/helper_selection.json, not here.",
            "Regenerate after structural HLD changes that affect toolchain requirements.",
        ],
    }


def build_source_package_content(
    target_root: Path,
    hld_text: str,
    *,
    hld_source_ref: str,
    state: str = "SOURCE_PACKAGE_IMPORTED",
    project_name: str = "",
    layout: str = "new",
    materialize_mirror: bool = True,
    source_sha256: str | None = None,
) -> SourcePackageBuild:
    """Real content flow: turn an HLD into the full source-package content.

    Writes HLD.md, HLD.marked.md, hld_reference_map.json,
    speckit_single_spec_input.md, then the manifest + metadata, then optionally
    regenerates the .specify/source/ mirror. Returns a structured build result
    (does not raise on content findings — unsupported claims surface for the
    gate, matching the SourcePackageValidation pattern).
    """
    # Imported here to avoid an import cycle (those modules import this one).
    from . import hld_marking, single_spec_input, implementation_slicing, engineering_selection

    adapter = TargetWorkspaceAdapter(target_root=target_root, layout=layout)
    source_dir = adapter.source_package_dir
    source_dir.mkdir(parents=True, exist_ok=True)

    (source_dir / AUTHORITATIVE_FILES["hld"]).write_text(hld_text, encoding="utf-8")
    (source_dir / AUTHORITATIVE_FILES["marked_hld"]).write_text(
        hld_marking.build_marked_hld(hld_text), encoding="utf-8"
    )
    ref_map = hld_marking.build_reference_map(hld_text)
    write_json_dict(source_dir / AUTHORITATIVE_FILES["reference_map"], ref_map)

    spec_input = single_spec_input.build_single_spec_input(hld_text, project_name=project_name)
    (source_dir / AUTHORITATIVE_FILES["single_spec_input"]).write_text(spec_input, encoding="utf-8")

    for filename, content in implementation_slicing.build_implementation_slicing_artifacts().items():
        (source_dir / filename).write_text(content, encoding="utf-8")

    (source_dir / AUTHORITATIVE_FILES["engineering_guidelines"]).write_text(
        engineering_selection.render_engineering_guidelines_md(hld_text, project_name=project_name),
        encoding="utf-8",
    )

    write_json_dict(
        source_dir / AUTHORITATIVE_FILES["helper_recommendations"],
        build_helper_recommendations(),
    )

    valid_anchors = set(ref_map["anchors"].keys())
    unsupported = single_spec_input.find_unsupported_claims(spec_input, valid_anchors)
    marking_errors = hld_marking.anchor_integrity_errors(hld_text)

    write_source_package(
        source_dir,
        hld_source_ref=hld_source_ref,
        state=state,
        target_root=target_root,
        source_sha256=source_sha256 or _source_file_sha256(hld_source_ref),
    )
    validation = validate_source_package(source_dir)
    mirrored: list[str] = []
    if materialize_mirror:
        mirrored = materialize_specify_mirror(source_dir, adapter.specify_source_mirror_dir)

    try:
        mediator_guidance.write_mediator_guidance_artifacts(target_root)
    except Exception as exc:
        raise RuntimeError(
            f"failed to write Journey 3 mediator guidance artifacts under {target_root}: {exc}"
        ) from exc

    return SourcePackageBuild(
        source_dir=source_dir,
        anchor_count=len(valid_anchors),
        unsupported_claims=unsupported,
        validation=validation,
        mirrored=mirrored,
        marking_errors=marking_errors,
    )
