"""``hldspec refresh-target``: safely refresh target-side HLDspec/SpecKit support files.

This is Journey 3 layer 3 (after the read-only next-feature readiness driver and
the target-side agent-guidance bootstrap). It is the *only* HLDspec capability
that writes into a target repo's support/governance/helper files, and it does so
under a strict, file-by-file safety classification.

Refresh may write:

- ``next_feature_AGENTS.md`` under the HLDspec control sync dir -- a pure
  HLDspec-generated helper, always safe to regenerate.
- ``.hldspec/bin/run-card`` -- a pure HLDspec-generated, read-only wrapper that
  runs the real readiness implementation against ``$PWD`` so an agent/human
  inside the target repo never needs to know the HLDspec checkout path. Always
  safe to regenerate.
- ``.specify/memory/constitution.md`` -- a governed SpecKit file, refreshed only
  through a managed marker block (see ``MANAGED_BEGIN``/``MANAGED_END``). Content
  outside the markers is project-owned and is never modified.

Refresh never:

- modifies product source code, tests, or anything under ``specs/``,
- resets, stashes, cleans, or overwrites uncommitted user work,
- creates or resets branches, runs SpecKit, or commits/pushes/merges,
- overwrites a constitution that has no managed markers -- that file is reported
  as ``EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW`` and a review/merge plan is
  written alongside it instead.

An existing unmarked constitution can be adopted into managed-block mode only
through the explicit ``--adopt-constitution-managed-block`` step (never plain
``--apply``): it backs the file up, inserts the managed block at the top, and
preserves every existing byte below it. Partial/malformed markers are reported
as ``CONFLICT_REQUIRES_HUMAN`` and never adopted.

This module performs no status/gap detection -- that remains
``next_feature_readiness`` ("speckit status" / "SpecKit run card"). Refresh and
status are deliberately separate: refresh writes a small set of governed files,
status only ever reads.
"""
from __future__ import annotations

import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable

from . import control_paths
from . import next_feature_agents_md as nfa
from .spec_bundles import utc_now

SCHEMA_VERSION = 1

# Classification labels (the safety model).
MISSING_CAN_CREATE = "MISSING_CAN_CREATE"
OWNED_BY_HLDSPEC_SAFE_TO_UPDATE = "OWNED_BY_HLDSPEC_SAFE_TO_UPDATE"
OWNED_BY_SPECKIT_SAFE_TO_REFRESH = "OWNED_BY_SPECKIT_SAFE_TO_REFRESH"
EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW = "EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW"
EXISTS_BUT_UNOWNED_DO_NOT_TOUCH = "EXISTS_BUT_UNOWNED_DO_NOT_TOUCH"
CONFLICT_REQUIRES_HUMAN = "CONFLICT_REQUIRES_HUMAN"
PRODUCT_FILE_NEVER_TOUCH = "PRODUCT_FILE_NEVER_TOUCH"

PLANNED_CLASSIFICATIONS = (
    MISSING_CAN_CREATE,
    OWNED_BY_HLDSPEC_SAFE_TO_UPDATE,
    OWNED_BY_SPECKIT_SAFE_TO_REFRESH,
)
CONFLICT_CLASSIFICATIONS = (
    EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW,
    CONFLICT_REQUIRES_HUMAN,
)

CONSTITUTION_RELPATH = Path(".specify") / "memory" / "constitution.md"
CONSTITUTION_BACKUP_SUFFIX = ".hldspec-bak"
CONSTITUTION_REVIEW_PLAN_FILE = "constitution_refresh_review.md"

# Target-local read-only run-card wrapper. Lives under the target's `.hldspec`
# dir so an agent/human inside the target repo can run `.hldspec/bin/run-card`
# without knowing the HLDspec checkout path.
RUN_CARD_RELPATH = Path(".hldspec") / "bin" / "run-card"
RUN_CARD_READINESS_SCRIPT = "scripts/next_feature_readiness_report.py"
# The HLDspec checkout this module belongs to, recorded into the generated
# wrapper as a default so it works with zero configuration; $HLDSPEC_HOME
# always overrides it.
HLDSPEC_ROOT = Path(__file__).resolve().parents[1]


def run_card_wrapper(hldspec_root: Path = HLDSPEC_ROOT) -> str:
    """Build the read-only target-local run-card wrapper script.

    Resolves the HLDspec implementation from `$HLDSPEC_HOME` first, then the
    path recorded at generation time, then fails with a clear instruction.
    Calls the real readiness implementation against `$PWD`; it never writes.
    """
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "# HLDspec target-local SpecKit run card -- READ-ONLY.",
            "#",
            "# Generated and regenerated by `hldspec refresh-target`. Do not hand-edit;",
            "# changes are overwritten on the next refresh.",
            "#",
            "# Prints this repo's SpecKit run card by calling the real HLDspec readiness",
            "# implementation. It only reads this repo's files and git state -- it never",
            "# runs SpecKit, installs hooks, creates branches, commits, pushes, or edits",
            "# product code/specs.",
            "#",
            "# Usage (from anywhere inside the target repo):",
            "#   .hldspec/bin/run-card",
            "#",
            "# HLDspec location is resolved in this order:",
            "#   1. $HLDSPEC_HOME, if set",
            "#   2. the path recorded when this wrapper was generated (below)",
            "#   3. otherwise: a clear error asking you to set HLDSPEC_HOME",
            "set -euo pipefail",
            "",
            f'RECORDED_HLDSPEC_HOME="{hldspec_root}"',
            'HLDSPEC_HOME="${HLDSPEC_HOME:-$RECORDED_HLDSPEC_HOME}"',
            f'READINESS="$HLDSPEC_HOME/{RUN_CARD_READINESS_SCRIPT}"',
            "",
            'if [ ! -f "$READINESS" ]; then',
            '  echo "run-card: HLDspec implementation not found at \'$HLDSPEC_HOME\'." >&2',
            '  echo "run-card: set HLDSPEC_HOME to your HLDspec checkout, e.g." >&2',
            '  echo "  HLDSPEC_HOME=/path/to/HLDspec $0" >&2',
            "  exit 1",
            "fi",
            "",
            '# Read-only: defaults to this repo ($PWD); extra args (e.g. --emit-agents-md) pass through.',
            'exec python3 "$READINESS" --target "$PWD" "$@"',
            "",
        ]
    )

MANAGED_BEGIN = "<!-- HLDSPEC:MANAGED:CONSTITUTION:BEGIN -->"
MANAGED_END = "<!-- HLDSPEC:MANAGED:CONSTITUTION:END -->"

# Explicit, user-approved adoption flag/command for taking an existing unmarked
# constitution into managed-block mode. Adoption is never performed by plain
# `--apply`; it requires this flag.
ADOPT_FLAG = "--adopt-constitution-managed-block"
ADOPT_COMMAND = f"python3 scripts/hldspec_refresh_target.py --target <target> {ADOPT_FLAG}"

# Marker states for an existing constitution.
MARKER_MANAGED = "MANAGED"      # both markers present and well-ordered
MARKER_PARTIAL = "PARTIAL"      # exactly one marker, or markers malformed/out of order
MARKER_UNMARKED = "UNMARKED"    # neither marker present

# Adoption result states (for the `adoption` field of an ADOPTED-mode result).
ADOPTION_PERFORMED = "ADOPTED"
ADOPTION_ALREADY_MANAGED = "ALREADY_MANAGED"
ADOPTION_PARTIAL_MARKERS_CONFLICT = "PARTIAL_MARKERS_CONFLICT"
ADOPTION_MISSING_CONSTITUTION = "MISSING_CONSTITUTION"


def _constitution_marker_state(text: str) -> str:
    """Classify managed-marker presence: MANAGED / PARTIAL / UNMARKED."""
    has_begin = MANAGED_BEGIN in text
    has_end = MANAGED_END in text
    if has_begin and has_end:
        return MARKER_MANAGED if _split_managed_block(text) is not None else MARKER_PARTIAL
    if has_begin or has_end:
        return MARKER_PARTIAL
    return MARKER_UNMARKED


def _managed_block_body() -> str:
    # NOTE: never embed the literal MANAGED_BEGIN/MANAGED_END marker strings in
    # this body. `_split_managed_block` locates the block by the first END marker
    # after BEGIN; a literal marker inside the body would be matched instead of
    # the real trailing marker and corrupt managed refresh.
    lines = [
        "## HLDspec/SpecKit Operating Principles (managed by `hldspec refresh-target`)",
        "",
        "These rules are regenerated by `hldspec refresh-target` and must not be",
        "hand-edited within this block. Project-specific rules belong below this",
        "managed block's end marker and are never modified by refresh.",
        "",
        "1. **SpecKit ritual order.** Features move through "
        "`/speckit.specify -> /speckit.clarify -> /speckit.plan -> /speckit.tasks "
        "-> /speckit.analyze -> /speckit.implement` in order. No phase is skipped.",
        "2. **Source of truth.** `specs/<branch>/spec.md`, `plan.md`, and `tasks.md` "
        "are the source of truth for an in-progress feature. This constitution "
        "governs all of them.",
        "3. **HLDspec is read-only navigation.** HLDspec tooling "
        "(`next_feature_readiness.py`, `hldspec refresh-target`) inspects this repo "
        "and reports phase/gaps/refresh status; it does not write specs, plans, "
        "tasks, or product code.",
        "4. **No silent execution.** SpecKit phases and git operations (commit, "
        "push, PR, merge) require an explicit human-run command. Nothing in this "
        "repo's HLDspec tooling runs them automatically.",
        "5. **Testing requirement.** Each feature's `tasks.md` must include unit "
        "test tasks, and UI/UX or integration test tasks where the feature has "
        "user-facing or cross-component behavior.",
        "6. **Clarification discipline.** `[NEEDS CLARIFICATION]` markers in "
        "`spec.md` must be resolved via `/speckit.clarify` before `/speckit.plan` "
        "proceeds.",
        "7. **Constitution change process.** Changes within this managed block come "
        "only from `hldspec refresh-target`. Changes below this block are owned by "
        "this project and are never modified by refresh.",
    ]
    return "\n".join(lines)


def managed_block() -> str:
    return f"{MANAGED_BEGIN}\n{_managed_block_body()}\n{MANAGED_END}"


def full_constitution_template() -> str:
    return "\n".join(
        [
            "# Project Constitution",
            "",
            managed_block(),
            "",
            "## Project-Specific Rules",
            "",
            "_Add project-specific architecture, quality, and governance rules below. "
            f"This section is owned by this project; `hldspec refresh-target` will "
            f"never modify or remove content below the `{MANAGED_END}` marker._",
            "",
        ]
    )


def _split_managed_block(text: str) -> tuple[str, str, str] | None:
    """Split `text` into (before, managed_block_text, after) if both markers are present, in order."""
    begin = text.find(MANAGED_BEGIN)
    if begin == -1:
        return None
    end = text.find(MANAGED_END, begin)
    if end == -1:
        return None
    end_with_marker = end + len(MANAGED_END)
    return text[:begin], text[begin:end_with_marker], text[end_with_marker:]


def refresh_constitution_text(existing: str) -> str:
    """Return `existing` with its managed block replaced by the current managed block.

    Caller must already have confirmed both markers are present (see `_split_managed_block`).
    """
    split = _split_managed_block(existing)
    if split is None:
        raise ValueError("constitution text has no managed block to refresh")
    before, _old_block, after = split
    return f"{before}{managed_block()}{after}"


@dataclass
class FileItem:
    path: str
    classification: str
    reason: str
    action: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


def _run_git(
    target: Path,
    argv: list[str],
    *,
    run: Callable[..., subprocess.CompletedProcess[str]] | None = None,
) -> subprocess.CompletedProcess[str]:
    runner = run or subprocess.run
    return runner(
        ["git", "-C", str(target), *argv],
        cwd=str(target),
        text=True,
        capture_output=True,
        check=False,
    )


def _git_text(
    target: Path,
    argv: list[str],
    *,
    run: Callable[..., subprocess.CompletedProcess[str]] | None = None,
) -> str | None:
    try:
        completed = _run_git(target, argv, run=run)
    except Exception:
        return None
    if completed.returncode != 0:
        return None
    return completed.stdout.rstrip("\n")


def _git_branch(target: Path, *, run: Callable[..., subprocess.CompletedProcess[str]] | None = None) -> str | None:
    return _git_text(target, ["branch", "--show-current"], run=run) or None


def _git_dirty(target: Path, *, run: Callable[..., subprocess.CompletedProcess[str]] | None = None) -> bool | None:
    porcelain = _git_text(target, ["status", "--porcelain"], run=run)
    if porcelain is None:
        return None
    return bool(porcelain.strip())


def _classify_agents_md(target: Path) -> FileItem:
    sync = control_paths.resolve_control_sync_dir(target, create=False)
    path = sync / nfa.BOOTSTRAP_FILE
    rel = str(path.relative_to(target)) if path.is_relative_to(target) else str(path)
    if path.is_file():
        return FileItem(
            path=rel,
            classification=OWNED_BY_HLDSPEC_SAFE_TO_UPDATE,
            reason="Pure HLDspec-generated bootstrap; regenerated in full on every refresh.",
            action="Regenerate from the current next-feature readiness state.",
        )
    return FileItem(
        path=rel,
        classification=MISSING_CAN_CREATE,
        reason="HLDspec-generated bootstrap is not present yet.",
        action="Create from the current next-feature readiness state.",
    )


def _classify_run_card(target: Path) -> FileItem:
    hldspec_dir = control_paths.resolve_hldspec_dir(target)
    path = hldspec_dir / "bin" / "run-card"
    rel = str(path.relative_to(target)) if path.is_relative_to(target) else str(path)
    if path.is_file():
        return FileItem(
            path=rel,
            classification=OWNED_BY_HLDSPEC_SAFE_TO_UPDATE,
            reason="Pure HLDspec-generated read-only run-card wrapper; regenerated in full on every refresh.",
            action="Regenerate the target-local run-card wrapper.",
        )
    return FileItem(
        path=rel,
        classification=MISSING_CAN_CREATE,
        reason="Target-local run-card wrapper is not present yet.",
        action="Create the read-only `.hldspec/bin/run-card` wrapper so the repo is self-guiding.",
    )


def _classify_constitution(target: Path) -> FileItem:
    path = target / CONSTITUTION_RELPATH
    rel = str(CONSTITUTION_RELPATH)
    if not path.is_file():
        return FileItem(
            path=rel,
            classification=MISSING_CAN_CREATE,
            reason="No constitution exists yet.",
            action="Create from the HLDspec/SpecKit managed constitution template.",
        )
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return FileItem(
            path=rel,
            classification=CONFLICT_REQUIRES_HUMAN,
            reason=f"Constitution exists but could not be read: {exc}.",
            action="No write planned; a human must investigate the unreadable file.",
        )
    state = _constitution_marker_state(text)
    if state == MARKER_MANAGED:
        return FileItem(
            path=rel,
            classification=OWNED_BY_SPECKIT_SAFE_TO_REFRESH,
            reason="Constitution has the HLDspec managed marker block.",
            action=(
                "Back up the current file, then replace only the content between "
                f"`{MANAGED_BEGIN}` and `{MANAGED_END}`; everything else is preserved."
            ),
        )
    if state == MARKER_PARTIAL:
        return FileItem(
            path=rel,
            classification=CONFLICT_REQUIRES_HUMAN,
            reason=(
                "Constitution has exactly one HLDspec managed marker, or the markers are "
                "malformed/out of order. This cannot be safely refreshed or adopted."
            ),
            action=(
                "No write planned. A human must repair the markers (both "
                f"`{MANAGED_BEGIN}` and `{MANAGED_END}`, in order) or remove them before refresh/adoption."
            ),
        )
    return FileItem(
        path=rel,
        classification=EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW,
        reason="Constitution exists without HLDspec managed markers; it may contain project-specific edits.",
        action=(
            "Do not modify constitution.md without explicit approval. Run a review/merge plan, or "
            f"adopt the managed block explicitly with `{ADOPT_FLAG}` (backs up first, inserts the "
            f"`{MANAGED_BEGIN}` / `{MANAGED_END}` block at the top, preserves all existing content below)."
        ),
    )


def _constitution_review_plan_md(target: Path) -> str:
    rel = str(CONSTITUTION_RELPATH)
    lines = [
        "# Constitution Refresh Review",
        "",
        f"`{rel}` exists but has no HLDspec managed marker block "
        f"(`{MANAGED_BEGIN}` / `{MANAGED_END}`).",
        "",
        "`hldspec refresh-target` did not modify this file. To opt into managed",
        "refresh, either:",
        "",
        "**A. Adopt automatically (recommended, explicit + backed up):**",
        "",
        f"```\n{ADOPT_COMMAND}\n```",
        "",
        "This backs up the current file, inserts the managed block at the top, and",
        "preserves every existing project-owned section unchanged below it.",
        "",
        "**B. Adopt manually:**",
        "",
        "1. Review the current constitution content.",
        "2. Add the managed block below (or wherever the HLDspec operating",
        "   principles belong in this project's constitution), keeping all existing",
        "   project-specific rules elsewhere in the file.",
        "3. Re-run `hldspec refresh-target` -- future refreshes will then update only",
        "   the content between the markers.",
        "",
        "## Managed block to add",
        "",
        "```markdown",
        managed_block(),
        "```",
        "",
    ]
    return "\n".join(lines)


def build_refresh_plan(target: Path, *, run: Callable[..., subprocess.CompletedProcess[str]] | None = None) -> dict[str, Any]:
    target = Path(target).expanduser().resolve()
    branch = _git_branch(target, run=run)
    dirty = _git_dirty(target, run=run)

    items = [_classify_agents_md(target), _classify_run_card(target), _classify_constitution(target)]
    constitution_item = items[-1]

    planned = [item for item in items if item.classification in PLANNED_CLASSIFICATIONS]
    skipped = [item for item in items if item.classification == EXISTS_BUT_UNOWNED_DO_NOT_TOUCH]
    conflicts = [item for item in items if item.classification in CONFLICT_CLASSIFICATIONS]

    constitution_refresh_needed = constitution_item.classification in PLANNED_CLASSIFICATIONS

    # Adoption is available only for an existing, unmarked constitution.
    adoption_available = constitution_item.classification == EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW
    constitution_adoption = {
        "available": adoption_available,
        "reason": (
            "Constitution exists without HLDspec managed markers; normal refresh refuses to edit it. "
            "Adopt the managed block explicitly to opt in."
            if adoption_available
            else "Adoption is only offered for an existing constitution that has no managed markers."
        ),
        "command": ADOPT_COMMAND if adoption_available else None,
        "safety_promise": (
            "Backs up the current constitution first, inserts the managed block at the top, and "
            "preserves every existing project-owned section byte-for-byte below it."
        ),
    }

    if adoption_available:
        safe_next_action = (
            "Constitution exists without managed markers; normal refresh will not edit it. To opt in, run "
            f"`{ADOPT_COMMAND}` (backs up first, inserts the managed block, preserves your content), then "
            "re-run dry-run and `--apply` only if no conflicts remain."
        )
    elif conflicts:
        safe_next_action = (
            "Review the conflict files listed below (and any "
            f"`{CONSTITUTION_REVIEW_PLAN_FILE}` written under the HLDspec sync dir on "
            "`--apply`); no constitution write is planned until that review is resolved."
        )
    elif planned:
        safe_next_action = "Run with `--apply` to write the planned updates listed below."
    else:
        safe_next_action = "Nothing to refresh; target support files are already up to date."

    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": utc_now(),
        "mode": "DRY_RUN",
        "target": str(target),
        "git_branch": branch,
        "git_dirty": dirty,
        "items": [item.to_dict() for item in items],
        "planned_updates": [item.to_dict() for item in planned],
        "skipped_files": [item.to_dict() for item in skipped],
        "conflict_files": [item.to_dict() for item in conflicts],
        "constitution_status": constitution_item.to_dict(),
        "constitution_refresh_needed": constitution_refresh_needed,
        "constitution_adoption": constitution_adoption,
        "speckit_support_status": {
            "constitution": constitution_item.to_dict(),
            "note": "Refresh manages only the files listed in `items`; all other `.specify/` and `specs/` content is left untouched.",
        },
        "run_card_pointer": (
            "For gap/status detection (\"speckit status\" / \"SpecKit run card\"), run "
            "`python3 scripts/next_feature_readiness_report.py --target <target>`. "
            "refresh-target does not perform status/gap detection."
        ),
        "safe_next_action": safe_next_action,
    }


def apply_refresh_plan(target: Path, plan: dict[str, Any]) -> dict[str, Any]:
    """Apply the planned writes from `build_refresh_plan`. Idempotent and non-destructive."""
    target = Path(target).expanduser().resolve()
    written: list[str] = []
    backups: list[str] = []
    review_files: list[str] = []

    for item in plan.get("planned_updates", []):
        rel = item["path"]
        if rel == str(CONSTITUTION_RELPATH):
            const_path = target / CONSTITUTION_RELPATH
            const_path.parent.mkdir(parents=True, exist_ok=True)
            if item["classification"] == MISSING_CAN_CREATE:
                const_path.write_text(full_constitution_template(), encoding="utf-8")
            elif item["classification"] == OWNED_BY_SPECKIT_SAFE_TO_REFRESH:
                existing = const_path.read_text(encoding="utf-8")
                backup_path = const_path.with_name(const_path.name + CONSTITUTION_BACKUP_SUFFIX)
                backup_path.write_text(existing, encoding="utf-8")
                backups.append(str(backup_path.relative_to(target)))
                const_path.write_text(refresh_constitution_text(existing), encoding="utf-8")
            written.append(rel)
        elif rel.endswith(nfa.BOOTSTRAP_FILE):
            result = nfa.write_next_feature_agents_md(target)
            written.append(str(Path(result["agents_md"]).relative_to(target)))
        elif rel.endswith("run-card"):
            run_card_path = control_paths.resolve_hldspec_dir(target) / "bin" / "run-card"
            run_card_path.parent.mkdir(parents=True, exist_ok=True)
            run_card_path.write_text(run_card_wrapper(), encoding="utf-8")
            run_card_path.chmod(0o755)
            written.append(rel)
        else:  # pragma: no cover - defensive; no other planned classifications exist today
            raise ValueError(f"no apply handler for planned file: {rel}")

    for item in plan.get("conflict_files", []):
        if item["path"] == str(CONSTITUTION_RELPATH) and item["classification"] == EXISTS_WITH_LOCAL_CHANGES_REQUIRES_REVIEW:
            sync = control_paths.resolve_control_sync_dir(target, create=True)
            review_path = sync / CONSTITUTION_REVIEW_PLAN_FILE
            review_path.write_text(_constitution_review_plan_md(target), encoding="utf-8")
            review_files.append(str(review_path.relative_to(target)))

    return {"written_files": written, "backup_files": backups, "review_files": review_files}


def adopt_constitution_managed_block(
    target: Path,
    *,
    run: Callable[..., subprocess.CompletedProcess[str]] | None = None,
) -> dict[str, Any]:
    """Explicitly adopt an existing unmarked constitution into managed-block mode.

    Only ever touches ``.specify/memory/constitution.md``. Backs the file up,
    inserts the managed block at the top followed by a blank line, and preserves
    every existing byte below it. Refuses (no write) when the file is missing,
    already managed, or has partial/malformed markers.
    """
    target = Path(target).expanduser().resolve()
    path = target / CONSTITUTION_RELPATH
    rel = str(CONSTITUTION_RELPATH)

    # Decide and perform the write first, then build the result plan so it
    # reflects the *post*-adoption state (classification, conflicts, etc.).
    adoption: dict[str, Any]
    written: list[str] = []
    backups: list[str] = []

    if not path.is_file():
        adoption = {
            "state": ADOPTION_MISSING_CONSTITUTION,
            "performed": False,
            "details": "No constitution exists; adoption applies only to an existing unmarked constitution. "
            "Use normal refresh `--apply` to create a fresh managed constitution.",
            "backup_file": None,
            "adopted_file": None,
            "marker_lines": None,
        }
    else:
        text = path.read_text(encoding="utf-8")
        state = _constitution_marker_state(text)
        if state == MARKER_MANAGED:
            adoption = {
                "state": ADOPTION_ALREADY_MANAGED,
                "performed": False,
                "details": "Constitution already has the managed block; no adoption needed and no duplicate block written.",
                "backup_file": None,
                "adopted_file": rel,
                "marker_lines": None,
            }
        elif state == MARKER_PARTIAL:
            adoption = {
                "state": ADOPTION_PARTIAL_MARKERS_CONFLICT,
                "performed": False,
                "details": "Constitution has exactly one managed marker, or markers are malformed/out of order. "
                "Adoption refused; a human must repair or remove the markers first.",
                "backup_file": None,
                "adopted_file": rel,
                "marker_lines": None,
            }
        else:  # MARKER_UNMARKED: back up, then insert the managed block at the top.
            backup_path = path.with_name(path.name + CONSTITUTION_BACKUP_SUFFIX)
            backup_path.write_text(text, encoding="utf-8")
            block = managed_block()
            path.write_text(f"{block}\n\n{text}", encoding="utf-8")
            written = [rel]
            backups = [str(backup_path.relative_to(target))]
            adoption = {
                "state": ADOPTION_PERFORMED,
                "performed": True,
                "details": "Managed block inserted at the top; original content preserved unchanged below it.",
                "backup_file": str(backup_path.relative_to(target)),
                "adopted_file": rel,
                # Block is `BEGIN\n<body>\nEND`, inserted at line 1.
                "marker_lines": {"begin": 1, "end": block.count("\n") + 1},
            }

    result = dict(build_refresh_plan(target, run=run))
    result["mode"] = "ADOPTED"
    result["written_files"] = written
    result["backup_files"] = backups
    result["review_files"] = []
    result["adoption"] = adoption
    return result


def refresh_target(
    target: Path,
    *,
    apply: bool = False,
    adopt: bool = False,
    run: Callable[..., subprocess.CompletedProcess[str]] | None = None,
) -> dict[str, Any]:
    # Adoption is an explicit, standalone step: it never piggybacks on `--apply`
    # and writes only the constitution backup + adopted file.
    if adopt:
        return adopt_constitution_managed_block(target, run=run)
    plan = build_refresh_plan(target, run=run)
    if not apply:
        return plan
    result = apply_refresh_plan(target, plan)
    plan = dict(plan)
    plan["mode"] = "APPLIED"
    plan["written_files"] = result["written_files"]
    plan["backup_files"] = result["backup_files"]
    plan["review_files"] = result["review_files"]
    return plan


def _bullet_items(items: list[dict[str, str]]) -> list[str]:
    if not items:
        return ["- none"]
    lines = []
    for item in items:
        lines.append(f"- `{item['path']}` -- `{item['classification']}`")
        lines.append(f"  - reason: {item['reason']}")
        lines.append(f"  - action: {item['action']}")
    return lines


def _bullet_paths(paths: list[str]) -> list[str]:
    return [f"- `{path}`" for path in paths] if paths else ["- none"]


def _adoption_section(result: dict[str, Any]) -> list[str]:
    """Render the constitution-adoption guidance (dry-run) or outcome (ADOPTED)."""
    adoption = result.get("adoption")
    if adoption:  # ADOPTED-mode result
        lines = [
            "## Constitution adoption",
            "",
            f"- state: `{adoption.get('state')}`",
            f"- performed: `{str(bool(adoption.get('performed'))).lower()}`",
            f"- {adoption.get('details')}",
        ]
        if adoption.get("backup_file"):
            lines.append(f"- backup: `{adoption['backup_file']}`")
        if adoption.get("adopted_file"):
            lines.append(f"- adopted file: `{adoption['adopted_file']}`")
        if adoption.get("marker_lines"):
            ml = adoption["marker_lines"]
            lines.append(f"- managed block markers at lines {ml.get('begin')} (begin) and {ml.get('end')} (end)")
        if adoption.get("state") == ADOPTION_PERFORMED:
            lines.append(
                "- next: re-run dry-run (expect `OWNED_BY_SPECKIT_SAFE_TO_REFRESH`), then `--apply` only if no conflicts."
            )
        lines.append("")
        return lines
    info = result.get("constitution_adoption")
    if info and info.get("available"):  # dry-run with an unmarked constitution
        return [
            "## Constitution adoption available",
            "",
            f"- why normal refresh refused: {info.get('reason')}",
            f"- adopt with: `{info.get('command')}`",
            f"- safety: {info.get('safety_promise')}",
            "",
        ]
    return []


def render_refresh_report(result: dict[str, Any]) -> str:
    lines = [
        "# HLDspec Refresh Target",
        "",
        f"Mode: `{result.get('mode')}`",
        "",
        "## Target repo",
        "",
        f"- `{result.get('target')}`",
        "",
        "## Git branch",
        "",
        f"- `{result.get('git_branch')}`",
        "",
        "## Dirty state",
        "",
        f"- dirty: `{result.get('git_dirty')}`",
        "",
        "## Planned updates",
        "",
        *_bullet_items(result.get("planned_updates", [])),
        "",
        "## Skipped files",
        "",
        *_bullet_items(result.get("skipped_files", [])),
        "",
        "## Conflict files",
        "",
        *_bullet_items(result.get("conflict_files", [])),
        "",
        "## Constitution status",
        "",
        f"- `{result['constitution_status']['path']}` -- `{result['constitution_status']['classification']}`",
        f"  - {result['constitution_status']['reason']}",
        "",
        *_adoption_section(result),
        "## SpecKit support status",
        "",
        f"- {result['speckit_support_status']['note']}",
        "",
        "## Run-card/gap status pointer",
        "",
        f"- {result.get('run_card_pointer')}",
        "",
        "## Safe next action",
        "",
        f"- {result.get('safe_next_action')}",
        "",
    ]
    if result.get("mode") == "APPLIED":
        lines.extend(
            [
                "## Written files",
                "",
                *_bullet_paths(result.get("written_files", [])),
                "",
                "## Backup files",
                "",
                *_bullet_paths(result.get("backup_files", [])),
                "",
                "## Review files",
                "",
                *_bullet_paths(result.get("review_files", [])),
                "",
            ]
        )
    return "\n".join(lines)
