#!/usr/bin/env python3
"""Deterministic local smoke: tiny HLD -> source package -> mirror validation.

This smoke uses real local HLDspec source-package code only. It never invokes
SpecKit and never spawns Claude, Codex, Devin, or any other agent.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hldspec.hld_source_package import build_source_package_content

FIXTURE_DIR = ROOT / "tests_v2" / "fixtures"
DEFAULT_HLD_FIXTURE = FIXTURE_DIR / "tiny_smoke_HLD.md"
DEFAULT_EXPECTED_ARTIFACTS = FIXTURE_DIR / "expected_smoke_artifacts.txt"

SMOKE_SOURCE_NAME = "tiny_HLD.md"
SMOKE_TARGET_NAME = "target"
SMOKE_ANCHORS: tuple[str, ...] = ("HLD-001", "HLD-002", "HLD-003")

SOURCE_PACKAGE_DIR = ".hldspec/source_package"
SPECIFY_SOURCE_DIR = ".specify/source"
REFERENCE_MAP = f"{SOURCE_PACKAGE_DIR}/hld_reference_map.json"
SINGLE_SPEC_INPUT = f"{SOURCE_PACKAGE_DIR}/speckit_single_spec_input.md"

SLICE_POLICY_FILES: tuple[str, ...] = (
    f"{SOURCE_PACKAGE_DIR}/slice_execution_policy.md",
    f"{SOURCE_PACKAGE_DIR}/implementation_slicing_policy.md",
)


@dataclass
class SmokeRunResult:
    passed: bool
    temp_root: Path
    source_hld: Path
    target: Path
    failures: list[str] = field(default_factory=list)
    artifacts: list[str] = field(default_factory=list)
    tmux_session: str | None = None

    def to_json(self) -> dict[str, Any]:
        return {
            "passed": self.passed,
            "result": "PASS" if self.passed else "FAIL",
            "temp_root": str(self.temp_root),
            "source_hld": str(self.source_hld),
            "target": str(self.target),
            "failures": self.failures,
            "artifacts": self.artifacts,
            "tmux_session": self.tmux_session,
        }


def create_temp_root() -> Path:
    return Path(tempfile.mkdtemp(prefix="hldspec-smoke-", dir="/tmp"))


def _load_expected_artifacts(path: Path = DEFAULT_EXPECTED_ARTIFACTS) -> tuple[str, ...]:
    if not path.is_file():
        return ()
    return tuple(
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    )


def _copy_source_hld(temp_root: Path, fixture: Path) -> Path:
    source = temp_root / SMOKE_SOURCE_NAME
    source.write_text(fixture.read_text(encoding="utf-8"), encoding="utf-8")
    return source


def _relative_artifacts(target: Path) -> list[str]:
    if not target.exists():
        return []
    return sorted(
        str(path.relative_to(target))
        for path in target.rglob("*")
        if path.is_file()
    )


def _validate_expected_files(target: Path, failures: list[str]) -> None:
    expected = _load_expected_artifacts()
    for rel in expected:
        if not (target / rel).is_file():
            failures.append(f"missing expected artifact: {rel}")


def _validate_required_dirs(target: Path, failures: list[str]) -> None:
    for rel in (SOURCE_PACKAGE_DIR, SPECIFY_SOURCE_DIR):
        path = target / rel
        if not path.is_dir():
            failures.append(f"missing directory: {rel}")


def _validate_reference_map(target: Path, failures: list[str]) -> None:
    path = target / REFERENCE_MAP
    if not path.is_file():
        failures.append(f"missing reference map: {REFERENCE_MAP}")
        return
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        failures.append(f"hld_reference_map.json parse error: {exc}")
        return
    present = set(data.get("anchors", {}).keys())
    for anchor in SMOKE_ANCHORS:
        if anchor not in present:
            failures.append(f"anchor {anchor} missing from hld_reference_map.json")


def _validate_single_spec_input(target: Path, failures: list[str]) -> None:
    path = target / SINGLE_SPEC_INPUT
    if not path.is_file():
        failures.append(f"missing single spec input: {SINGLE_SPEC_INPUT}")
        return
    text = path.read_text(encoding="utf-8")
    for anchor in SMOKE_ANCHORS:
        if f"({anchor})" not in text:
            failures.append(f"anchor {anchor} not cited in speckit_single_spec_input.md")


def _validate_mirror(target: Path, failures: list[str]) -> None:
    mirror_dir = target / SPECIFY_SOURCE_DIR
    hld_mirror = mirror_dir / "HLD.md"
    if hld_mirror.is_file() and "GENERATED by HLDspec" not in hld_mirror.read_text(encoding="utf-8"):
        failures.append("mirror HLD.md missing GENERATED banner")


def _validate_slice_policy_if_present(target: Path, failures: list[str]) -> None:
    slices_path = target / SOURCE_PACKAGE_DIR / "implementation_slices.json"
    if slices_path.is_file():
        try:
            data = json.loads(slices_path.read_text(encoding="utf-8"))
        except Exception as exc:
            failures.append(f"implementation_slices.json parse error: {exc}")
            data = {}
        names = {item.get("name") for item in data.get("slices", []) if isinstance(item, dict)}
        for required in (
            "FOUNDATION",
            "WALKING_SKELETON",
            "DOMAIN_MODEL",
            "CONTRACTS",
            "BUSINESS_LOGIC",
            "PERSISTENCE",
            "API",
            "CLI",
            "UI",
            "INTEGRATION_HARDENING",
        ):
            if required not in names:
                failures.append(f"missing canonical slice: {required}")

    policy_paths = [target / rel for rel in SLICE_POLICY_FILES if (target / rel).is_file()]
    if not policy_paths:
        return
    policy_text = "\n".join(path.read_text(encoding="utf-8") for path in policy_paths)
    required_phrases = (
        "one complete specify",
        "one complete plan",
        "one complete task",
        "analyze",
        "controlled implementation",
    )
    lowered = policy_text.lower()
    for phrase in required_phrases:
        if phrase not in lowered:
            failures.append(f"slice policy missing phrase: {phrase}")


def _validate_no_generated_artifacts_outside_target(result: SmokeRunResult) -> None:
    allowed = {result.source_hld, result.target}
    for path in result.temp_root.iterdir():
        if path not in allowed:
            result.failures.append(f"unexpected temp-root artifact outside target: {path.name}")


def run_smoke(
    temp_root: Path,
    *,
    hld_fixture: Path = DEFAULT_HLD_FIXTURE,
    tmux_session: str | None = None,
) -> SmokeRunResult:
    """Run the smoke under temp_root and return structured validation results."""
    temp_root.mkdir(parents=True, exist_ok=True)
    source_hld = _copy_source_hld(temp_root, hld_fixture)
    target = temp_root / SMOKE_TARGET_NAME
    failures: list[str] = []

    build = build_source_package_content(
        target,
        source_hld.read_text(encoding="utf-8"),
        hld_source_ref=str(source_hld),
        state="SOURCE_PACKAGE_IMPORTED",
        project_name="Smoke Test Product",
        layout="new",
        materialize_mirror=True,
    )

    for err in build.marking_errors:
        failures.append(f"marking error: {err}")
    for claim in build.unsupported_claims:
        failures.append(f"unsupported claim: {claim}")
    for filename in build.validation.missing:
        failures.append(f"validation missing: {filename}")
    for filename in build.validation.hash_mismatches:
        failures.append(f"validation hash mismatch: {filename}")

    _validate_required_dirs(target, failures)
    _validate_expected_files(target, failures)
    _validate_reference_map(target, failures)
    _validate_single_spec_input(target, failures)
    _validate_mirror(target, failures)
    _validate_slice_policy_if_present(target, failures)

    result = SmokeRunResult(
        passed=not failures,
        temp_root=temp_root,
        source_hld=source_hld,
        target=target,
        failures=failures,
        artifacts=_relative_artifacts(target),
        tmux_session=tmux_session,
    )
    _validate_no_generated_artifacts_outside_target(result)
    result.passed = not result.failures
    return result


def _setup_tmux(temp_root: Path, session_name: str = "hldspec-smoke") -> str | None:
    """Create a tmux visibility session. Tmux state is not approval state."""
    if not shutil.which("tmux"):
        return None
    subprocess.run(
        ["tmux", "new-session", "-d", "-s", session_name, "-x", "220", "-y", "50"],
        capture_output=True,
        check=False,
    )
    subprocess.run(
        [
            "tmux",
            "send-keys",
            "-t",
            session_name,
            f"echo 'HLDspec smoke root: {temp_root}'",
            "Enter",
        ],
        capture_output=True,
        check=False,
    )
    return session_name


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="HLDspec deterministic local smoke: tiny HLD -> source package -> mirror validation."
    )
    parser.add_argument("--root", metavar="DIR", help="Use this temp root instead of creating /tmp/hldspec-smoke-XXXXXX.")
    parser.add_argument("--hld", metavar="FILE", default=str(DEFAULT_HLD_FIXTURE), help="Source HLD fixture to copy to <temp_root>/tiny_HLD.md.")
    parser.add_argument("--keep", action="store_true", help="Keep the temp root on completion.")
    parser.add_argument("--json", action="store_true", help="Emit a JSON summary before the final result line.")
    parser.add_argument("--tmux", action="store_true", help="Create a tmux visibility session if tmux is installed.")
    parser.add_argument("--attach", action="store_true", help="Attach to the tmux session after the smoke (implies --tmux).")
    args = parser.parse_args(argv)

    temp_root = Path(args.root).expanduser().resolve() if args.root else create_temp_root()
    hld_fixture = Path(args.hld).expanduser().resolve()
    tmux_session: str | None = None

    if args.tmux or args.attach:
        tmux_session = _setup_tmux(temp_root)
        if tmux_session is None:
            print("SKIP_TMUX: tmux not found; continuing without UI session.", file=sys.stderr)

    result = run_smoke(temp_root, hld_fixture=hld_fixture, tmux_session=tmux_session)

    if args.json:
        print(json.dumps(result.to_json(), indent=2, sort_keys=True))
    elif result.failures:
        for failure in result.failures:
            print(f"FAIL: {failure}", file=sys.stderr)

    if not args.keep:
        shutil.rmtree(temp_root, ignore_errors=True)

    if tmux_session and args.attach:
        subprocess.run(["tmux", "attach-session", "-t", tmux_session], check=False)

    print(f"HLDSPEC_SMOKE_RESULT: {'PASS' if result.passed else 'FAIL'}")
    return 0 if result.passed else 1


if __name__ == "__main__":
    sys.exit(main())
